### ISSUE TITLE
initial release todo + roadmap

### ISSUE THREAD

**Issue by simpixelated** [simpixelated/mobx-react-form-components-material#1]
## Initial Release
- [ ] extend airbnb eslint
- [ ] setup https://github.com/semantic-release/semantic-release
- [ ] add CHANGELOG.md
- [ ] update README.md
- [ ] init package.json
- [ ] support for Material UI TextField
- [ ] support for Material UI Toggle

### Short term:
- support for [Material UI DatePicker](http://www.material-ui.com/#/components/date-picker)
- support for [Material UI SelectField](http://www.material-ui.com/#/components/select-field)
- ability to override some default props on the components of original UI packages.
- easy theming options and custom styles overriding (based on UI packages).

### Longer term:
- support for SSR (server side rendering).
-  props for easy inline/block and aligning components (without dealing with style).
- flexible, customizable and extensible form buttons and controls (submit, clear, reset, add, del) with options and actions.
- support for special actions (add/del) and special conditions (hide/show) for components blocks such as fieldsets and controls. (for example show that fieldset (with specific inputs) if the this checkbox is true, etc...).
- nice to have for quick CRUD development would be the ability to create form layouts defining inputs, validation and layout structure describing it in a simple javascript object.
- follow the mobx-react-form naming conventions (we may discuss and align us during the development as I'm rethinking some apis for the next major release).

See discussion of generic component support at https://github.com/foxhound87/mobx-react-form-demo/issues/1

**Comment by foxhound87** [comment]
Now [Fields Properties Bindings](https://foxhound87.github.io/mobx-react-form/docs/bindings/) are availables. I think you will find this very useful!
